# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created: Tue Jan 21 23:08:38 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1200, 759)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.boutons = QtGui.QVBoxLayout()
        self.boutons.setSpacing(0)
        self.boutons.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.boutons.setContentsMargins(-1, -1, 1, 1)
        self.boutons.setObjectName(_fromUtf8("boutons"))
        self.photo = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.photo.sizePolicy().hasHeightForWidth())
        self.photo.setSizePolicy(sizePolicy)
        self.photo.setMinimumSize(QtCore.QSize(250, 200))
        self.photo.setMaximumSize(QtCore.QSize(250, 200))
        self.photo.setBaseSize(QtCore.QSize(0, 0))
        self.photo.setText(_fromUtf8(""))
        self.photo.setTextFormat(QtCore.Qt.AutoText)
        self.photo.setScaledContents(True)
        self.photo.setObjectName(_fromUtf8("photo"))
        self.boutons.addWidget(self.photo)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.boutons.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.boutons.addItem(spacerItem1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.boutons.addItem(spacerItem2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.visuBal2 = QtGui.QLCDNumber(self.centralwidget)
        self.visuBal2.setEnabled(False)
        self.visuBal2.setMinimumSize(QtCore.QSize(180, 70))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.visuBal2.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.visuBal2.setFont(font)
        self.visuBal2.setDigitCount(7)
        self.visuBal2.setProperty("value", 24.22)
        self.visuBal2.setObjectName(_fromUtf8("visuBal2"))
        self.gridLayout_2.addWidget(self.visuBal2, 2, 1, 1, 1)
        self.visuBal1 = QtGui.QLCDNumber(self.centralwidget)
        self.visuBal1.setEnabled(True)
        self.visuBal1.setMinimumSize(QtCore.QSize(180, 70))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.visuBal1.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.visuBal1.setFont(font)
        self.visuBal1.setSmallDecimalPoint(False)
        self.visuBal1.setNumDigits(7)
        self.visuBal1.setDigitCount(7)
        self.visuBal1.setProperty("value", 120.333)
        self.visuBal1.setObjectName(_fromUtf8("visuBal1"))
        self.gridLayout_2.addWidget(self.visuBal1, 1, 1, 1, 1)
        self.selBal1 = QtGui.QRadioButton(self.centralwidget)
        self.selBal1.setChecked(True)
        self.selBal1.setObjectName(_fromUtf8("selBal1"))
        self.gridLayout_2.addWidget(self.selBal1, 1, 2, 1, 1)
        self.selBal2 = QtGui.QRadioButton(self.centralwidget)
        self.selBal2.setObjectName(_fromUtf8("selBal2"))
        self.gridLayout_2.addWidget(self.selBal2, 2, 2, 1, 1)
        self.boutons.addLayout(self.gridLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.boutons.addItem(spacerItem3)
        self.pbTare = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbTare.sizePolicy().hasHeightForWidth())
        self.pbTare.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pbTare.setFont(font)
        self.pbTare.setObjectName(_fromUtf8("pbTare"))
        self.boutons.addWidget(self.pbTare)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.boutons.addItem(spacerItem4)
        self.pbPesee = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pbPesee.setFont(font)
        self.pbPesee.setObjectName(_fromUtf8("pbPesee"))
        self.boutons.addWidget(self.pbPesee)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.boutons.addItem(spacerItem5)
        self.pbImprimer = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pbImprimer.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("imprimante.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbImprimer.setIcon(icon)
        self.pbImprimer.setIconSize(QtCore.QSize(50, 50))
        self.pbImprimer.setFlat(False)
        self.pbImprimer.setObjectName(_fromUtf8("pbImprimer"))
        self.boutons.addWidget(self.pbImprimer)
        self.gridLayout.addLayout(self.boutons, 6, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Sans Serif"))
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(32, 32))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.listWidget = QtGui.QListWidget(self.tab)
        self.listWidget.setEnabled(True)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 1231, 751))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidget.setFont(font)
        self.listWidget.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.listWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget.setAutoFillBackground(False)
        self.listWidget.setStyleSheet(_fromUtf8(""))
        self.listWidget.setFrameShadow(QtGui.QFrame.Raised)
        self.listWidget.setEditTriggers(QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.listWidget.setIconSize(QtCore.QSize(100, 80))
        self.listWidget.setMovement(QtGui.QListView.Static)
        self.listWidget.setFlow(QtGui.QListView.TopToBottom)
        self.listWidget.setResizeMode(QtGui.QListView.Adjust)
        self.listWidget.setLayoutMode(QtGui.QListView.Batched)
        self.listWidget.setGridSize(QtCore.QSize(140, 120))
        self.listWidget.setViewMode(QtGui.QListView.IconMode)
        self.listWidget.setModelColumn(0)
        self.listWidget.setUniformItemSizes(True)
        self.listWidget.setBatchSize(100)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 6, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Fichiers = QtGui.QMenu(self.menubar)
        self.menu_Fichiers.setObjectName(_fromUtf8("menu_Fichiers"))
        self.menuBalonce_1 = QtGui.QMenu(self.menubar)
        self.menuBalonce_1.setObjectName(_fromUtf8("menuBalonce_1"))
        self.menuBalance_2 = QtGui.QMenu(self.menubar)
        self.menuBalance_2.setObjectName(_fromUtf8("menuBalance_2"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionEn_Ligne = QtGui.QAction(MainWindow)
        self.actionEn_Ligne.setCheckable(True)
        self.actionEn_Ligne.setChecked(True)
        self.actionEn_Ligne.setObjectName(_fromUtf8("actionEn_Ligne"))
        self.actionE_tallonage = QtGui.QAction(MainWindow)
        self.actionE_tallonage.setObjectName(_fromUtf8("actionE_tallonage"))
        self.actionEn_Ligne_2 = QtGui.QAction(MainWindow)
        self.actionEn_Ligne_2.setCheckable(True)
        self.actionEn_Ligne_2.setChecked(True)
        self.actionEn_Ligne_2.setObjectName(_fromUtf8("actionEn_Ligne_2"))
        self.actionE_talonnage = QtGui.QAction(MainWindow)
        self.actionE_talonnage.setObjectName(_fromUtf8("actionE_talonnage"))
        self.action_Quitter = QtGui.QAction(MainWindow)
        self.action_Quitter.setObjectName(_fromUtf8("action_Quitter"))
        self.menu_Fichiers.addAction(self.action_Quitter)
        self.menuBalonce_1.addSeparator()
        self.menuBalonce_1.addAction(self.actionEn_Ligne)
        self.menuBalonce_1.addAction(self.actionE_tallonage)
        self.menuBalance_2.addAction(self.actionEn_Ligne_2)
        self.menuBalance_2.addAction(self.actionE_talonnage)
        self.menubar.addAction(self.menu_Fichiers.menuAction())
        self.menubar.addAction(self.menuBalonce_1.menuAction())
        self.menubar.addAction(self.menuBalance_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Balance", None))
        self.label.setText(_translate("MainWindow", "SELECTIONNER UN PRODUIT", None))
        self.selBal1.setText(_translate("MainWindow", "Balance 1", None))
        self.selBal2.setText(_translate("MainWindow", "Balance 2", None))
        self.pbTare.setToolTip(_translate("MainWindow", "<html><head/><body><p>poid du panier</p></body></html>", None))
        self.pbTare.setText(_translate("MainWindow", "Tare\n"
"0 kg", None))
        self.pbPesee.setToolTip(_translate("MainWindow", "<html><head/><body><p>Poid sans le panier<br/>(poid total)</p></body></html>", None))
        self.pbPesee.setText(_translate("MainWindow", "Pesée\n"
"0 kg (0 kg)", None))
        self.pbImprimer.setToolTip(_translate("MainWindow", "<html><head/><body><p>Date<br/><span style=\" font-weight:600;\">Pas de référence</span><br/>Pas de nom<br/><span style=\" font-weight:600;\">Poid :</span> 0 kg<br/><span style=\" font-weight:600;\">Qté :</span> 0</p></body></html>", None))
        self.pbImprimer.setText(_translate("MainWindow", "pas de réference\n"
"pas de nom\n"
"0 pièces", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Carters", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Supports", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Autres...", None))
        self.menu_Fichiers.setTitle(_translate("MainWindow", "&Fichier", None))
        self.menuBalonce_1.setTitle(_translate("MainWindow", "B&alance1", None))
        self.menuBalance_2.setTitle(_translate("MainWindow", "&Balance2", None))
        self.actionEn_Ligne.setText(_translate("MainWindow", "En &Ligne", None))
        self.actionE_tallonage.setText(_translate("MainWindow", "E&talonnage", None))
        self.actionEn_Ligne_2.setText(_translate("MainWindow", "En &Ligne", None))
        self.actionE_talonnage.setText(_translate("MainWindow", "E&talonnage", None))
        self.action_Quitter.setText(_translate("MainWindow", "&Quitter", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    for i in range(10):
        ui.listWidget.addItem('你妹啊')


    MainWindow.show()
    sys.exit(app.exec_())